# Generated by Django 3.2.12 on 2022-05-22 19:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrupaRobocza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=15)),
                ('aktywna', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Narzedzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupa', models.CharField(max_length=15)),
                ('uwagi', models.CharField(blank=True, max_length=150, null=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Przekroje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('przekrojPrzewodu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rozciagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zlecenia', models.CharField(max_length=10)),
                ('nr_pozycji', models.CharField(max_length=250)),
                ('lista', models.CharField(choices=[('lista', 'Lista połączeń'), ('zlecenie', 'Zlecenie produkcyjne')], default='lista', max_length=15)),
                ('nr_pracownika', models.DecimalField(decimal_places=0, max_digits=5)),
                ('rozciag', models.DecimalField(decimal_places=0, max_digits=5)),
                ('indeks_kontaktu', models.CharField(max_length=10)),
                ('poprawkowe', models.BooleanField(default=False)),
                ('narzedzia', models.CharField(max_length=20)),
                ('wysokosc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('data_serwis', models.DateTimeField(blank=True, null=True, verbose_name='data serwis')),
                ('data_dodania', models.DateTimeField(default=datetime.datetime.now, verbose_name='data dodania')),
                ('potwierdzenie', models.BooleanField(default=False)),
                ('grupa_robocza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciagi_v2.gruparobocza')),
                ('narzedzia_rodzaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciagi_v2.narzedzia')),
                ('przekrojePrzewodow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciagi_v2.przekroje')),
                ('zalogowany_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rozciagi_v2.author')),
            ],
        ),
    ]
