# Generated by Django 3.2.12 on 2022-05-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciagi_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przekroje',
            name='przekrojPrzewodu',
            field=models.CharField(max_length=7),
        ),
    ]
