# Generated by Django 3.2.12 on 2022-05-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rozciagi_v2', '0002_alter_przekroje_przekrojprzewodu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('aktywna', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rozciagi',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozciagi_v2.listy'),
        ),
    ]
