# Generated by Django 3.2.12 on 2022-05-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciagi_v2', '0003_auto_20220523_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przekroje',
            name='przekrojPrzewodu',
        ),
        migrations.AddField(
            model_name='przekroje',
            name='nazwa',
            field=models.CharField(default=0.1, max_length=7),
            preserve_default=False,
        ),
    ]
