# Generated by Django 3.2.12 on 2022-05-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciagi_v2', '0004_auto_20220529_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozciagi',
            name='data_dodania',
            field=models.DateField(verbose_name='data dodania'),
        ),
        migrations.AlterField(
            model_name='rozciagi',
            name='data_serwis',
            field=models.DateField(blank=True, null=True, verbose_name='data serwis'),
        ),
    ]
