# Generated by Django 3.2.12 on 2022-05-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rozciagi_v2', '0005_auto_20220530_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rozciagi',
            name='data_dodania',
        ),
        migrations.RemoveField(
            model_name='rozciagi',
            name='data_serwis',
        ),
    ]
