# Generated by Django 3.2.12 on 2022-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozciagi_v2', '0006_auto_20220530_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='rozciagi',
            name='data_dodania',
            field=models.DateField(blank=True, null=True, verbose_name='data dodania'),
        ),
        migrations.AddField(
            model_name='rozciagi',
            name='data_serwis',
            field=models.DateField(blank=True, null=True, verbose_name='data serwis'),
        ),
    ]
